### ISSUE TITLE
example of storing tokens? 

### ISSUE THREAD

**Issue by austintrombley** [box/box-python-sdk#132]
can you give an example of this?  What is a keychain?

def store_tokens(access_token, refresh_token):
    # store the tokens at secure storage (e.g. Keychain)

**Comment by kthurimella** [comment]
You could use Redis to store them or any type of DB:

```
    @classmethod
    def store_tokens(cls, access_token, refresh_token):
        """
        This callback method stores the access token and refresh token that box requires.
        Args:
            access_token: token access the app
            refresh_token:  token to refresh the access token

        Returns: None

        """
        redis = RedisClient()
        redis_value = json.dumps({'access_token': access_token, 'refresh_token': refresh_token})
        redis.set("box_api_tokens", redis_value)
```

**Comment by jmoldow** [comment]
Thanks @kthurimella for the suggestion. Also, see our example Redis implementation, in case it is useful to you: https://github.com/box/box-python-sdk/blob/master/boxsdk/auth/redis_managed_oauth2.py.

@austintrombley : I wouldn't worry about `store_tokens`, unless it is something that you know your application definitely needs to do. The average application probably doesn't need to use this feature. And using it unnecessarily or incorrectly can leave your tokens sitting around insecurely, which is bad.

One reason one might use `store_tokens` is if the application uses multiple processes or is spread out over multiple machines, and needs to coordinate auth. In that case, the process that does token refresh might need to store the new access token in a central location where other processes can access it. For example, see again our example Redis implementation, which I linked above.

Another reason might be to (securely) store the refresh token on the user's disk, that way the application can come back from a restart and continue working, without needing to redo the OAuth2 flow. One way to accomplish this would be with this library: https://pypi.python.org/pypi/keyring. The "Keychain" referred to is the secure storage on Mac OS X, which is used by keyring and other libraries/applications.

These are all examples, not advice. We're not security experts, which is why we don't try to make any suggestions about how to store tokens. Ideally, you wouldn't, unless you really have to, in which case you need to decide what is the most secure approach for your application, target platform, etc.

**Comment by austintrombley** [comment]
Sure, but the code doesn’t work if I leave it blank…. So how do you use it without this feature / parameter?

regards,
Austin D. Trombley, MBA
Senior Manager – Business Intelligence
cell:  415-767-6179
[cid:image001.png@01D1D1F1.0252A830]<http://www.prosper.com/>
