### ISSUE TITLE
no refresh token

### ISSUE THREAD

**Issue by austintrombley** [box/box-python-sdk#133]
here is my code based on documentation

```
from boxsdk import OAuth2, Client
import os 
os.chdir('"C:/Users/atrombley/Desktop/Projects/cost_data_upload/')
oauth = OAuth2(
    client_id='...',
    client_secret='...',
)
auth_url, csrf_token = oauth.get_authorization_url('http://localhost:1410')
client = Client(oauth)
client.file(file_id='33618399925').content()
```
how do i get a refresh token?  The documentation here is really bad, my auth_url looks nothing like this:  http://YOUR_REDIRECT_URL?code=YOUR_AUTH_CODE

```
boxsdk.exception.BoxOAuthException: 
Message: {"error":"invalid_request","error_description":"No \"refresh_token\" parameter found"}
Status: 400
URL: https://api.box.com/oauth2/token
Method: POST
```

**Comment by eL-HaXo** [comment]
I am having the same issue.

**Comment by Jeff-Meadows** [comment]
Sorry you're having a tough time getting started with the SDK.

You need a user to visit the `auth url` and complete the login flow. The last step of that login flow will include navigation to your redirect url.

You should have a webserver running and ready to accept requests to that url; the handler for the request will need to parse the url and get the auth code out of it.

There's some example code in `demo/auth.py`.

If you have an idea on how to improve the docs, please open a PR or just make a suggestion here.

**Comment by austintrombley** [comment]
What if we don’t have a web server?  I am able to do this with boxR without a web server?  Just can’t do it from yours?

regards,
Austin D. Trombley, MBA
Senior Manager – Business Intelligence
cell:  415-767-6179
[cid:image001.png@01CFEA2B.2E127A90]<http://www.prosper.com/>

**Comment by eL-HaXo** [comment]
Thanks for your reply. I am building an application without a UI and took me a while to find the JWT docs but I think this is what we were looking for: https://box-content.readme.io/v2.0/docs/box-platform/

**Comment by jmoldow** [comment]
> What if we don’t have a web server? I am able to do this with boxR without a web server? Just can’t do it from yours?

Hi @austintrombley . If you are using Box Platform / app auth / app users, then you don't need a web server. Check out the documentation that @eL-HaXo linked to, and make sure to use `JWTAuth` or one of its subclasses.

However, if you are having users log into your application with their own Box accounts, then you must redirect to a web page that you control, which usually means running a web server to handle the redirects properly. This is because Box uses the OAuth2 protocol for user logins. Some references:

https://box-content.readme.io/reference#oauth-2
https://tools.ietf.org/html/rfc6749
https://box-content.readme.io/v2.0/docs/oauth-20
