### ISSUE TITLE
Issue with emails containing a +

### ISSUE THREAD

**Issue by kboparai1** [box/box-python-sdk#143]
Hello,

I'm wondering if the filter term is ignoring pluses +. When I attempt to run my script, it seems Box can't pass these type of email addresses? I also attempted to `myString.replace(“+”, “%2B”)` in hopes that this might resolve this issue. 

filter_term=target_login
example: kbop+1@mycompany.com

**Comment by Jeff-Meadows** [comment]
Hi @kboparai1 - can you elaborate on the issue you're having? Are you seeing an error message?

**Comment by kboparai1** [comment]
Hello! Sure thing.

Scenario: I have a bunch of folders named by user's email addresses that I'd eventually like to transfer into their respective owners box accounts.

Problem: There are no error messages. Any searches having a + in the email do not find a result.

**Comment by jmoldow** [comment]
Are you trying to use this endpoint:

https://docs.box.com/reference#get-all-users-in-an-enterprise
https://github.com/box/box-python-sdk/blob/master/boxsdk/client/client.py#L117

Can you use the `DevelopmentClient` so that we can see the logged HTTP requests and responses?

Can you also show the code your using to call `Client.users()`?

What version of `boxsdk` and `requests` are you using? What Python version?

**Comment by kboparai1** [comment]
boxsdk = 1.5.3
requests = 2.10.0

```
def get_user_by_login(b_client, target_login):
    results = b_client.users(filter_term=target_login)
    for u in results:
        if u.login == target_login:
            return u
```

GET https://api.box.com/2.0/users {'headers': {u'Authorization': u'Bearer mytoken',
             u'User-Agent': u'box-python-sdk-1.5.3'},
 'params': {u'filter_term': 'kbop+1@mycompany.com ', 'offset': 0}}
{"total_count":0,"entries":[],"limit":100,"offset":0}

GET https://api.box.com/2.0/users {'headers': {u'Authorization': u'Bearer mytoken',
             u'User-Agent': u'box-python-sdk-1.5.3'},
 'params': {u'filter_term': 'kbop%2B1@mycompany.com ', 'offset': 0}}
{"total_count":0,"entries":[],"limit":100,"offset":0}

I hope that is helpful.

**Comment by jmoldow** [comment]
That logging isn't as low-level as I was hoping. However, looking at `requests` code, it looks like it uses `urlparse.urlencode`. So `{u'filter_term': 'kbop%2B1@mycompany.com ', 'offset': 0}` would get turned into `?filter_term=kbop%2B1%40mycompany.com+&offset=0`, which I expect to be correct.

Passing `kbop%2B1@mycompany.com` won't work, because then the `%` itself gets encoded to `%25`.

I see you have an extra space at the end of both email addresses. That might be the cause of the problem. Remove the extra space and see if that works.

**Comment by kboparai1** [comment]
Ahh sorry that extra space is was my doing when I was swapping out the domain. 

Is there something else I could try?

**Comment by jmoldow** [comment]
I just tried something similar, and it worked fine for me. It doesn't seem to be a problem with the SDK. Either there is a bug in the Box API for some edge case that you're hitting, or the real username is somehow different than what you're providing, or the result is correct and there's a misunderstanding about what should be returned from that endpoint.

Make sure you re-read the various caveats listed at https://docs.box.com/reference#get-all-users-in-an-enterprise, in case your user falls into any of them (perhaps what you've entered has a mismatch, or perhaps your user is an external user instead of a managed user, or perhaps the user isn't even in the enterprise).
