### ISSUE TITLE
Mock Box does not response correctly to File.update_contents()

### ISSUE THREAD

**Issue by kelseymorris95** [box/box-python-sdk#150]
The structure of an API response during a call to `File.update_contents()` is documented here:
https://docs.box.com/reference#upload-a-new-version-of-a-file

The documented structure for a response is:
`{
    "total_count": 1,
    "entries": [
        {
            "type": "file",
            ...,
        }
    ]
}`

The current response received from Mock Box for the same API request in test/functional/test_file_upload_update_download.py is:
`{
"type": "file",
...,
}`

`Folder` also has an `upload()` method.  This method should receive a response object with the same structure as `File.update_content()`'s documented version, as documented below:
https://docs.box.com/reference#upload-a-file

In this case, a `Folder` object is built and returned with `box_response['entries'][0]` as its `response_object` member.

In `File.update_contents()`, the `response_object` member is set to the entire response instead, leading to an inconsistency in the way these two similar operations are handled.

**Comment by jmoldow** [comment]
Thanks for finding this @kelseymorris95 .

There are two possible correct things that we can do here to be consistent:
- Always return an `APIJSONObject`, with content `{"total_count": 1, "entries": [<Box File ...>]}`. This would require changes to both upload methods.
- Since there should only ever be exactly one entry, always return a `File`, with `response_data` for the file object. This is what `Folder.upload()` currently does, but as you noted, `File.update_contents()` erroneously puts the entire response as the `response_data`.

Either way, `File.update_contents()` is currently wrong, because `file.update_contents(...)['id']` fails.

**Comment by jmoldow** [comment]
This will be fixed in the 2.0.0a6 release.
