### ISSUE TITLE
Refresh token, access token usage behavior for desktop application

### ISSUE THREAD

**Issue by susamn** [box/box-python-sdk#185]
I am writing a python desktop box client utility application, which is required to get access to box.com via box SDK. Since its a desktop application, it's not running always so the SDK cannot refresh token automatically. So every time I start the application, I have to authenticate via the browser and get a new refresh and access token. It's a very bad practice. Am I missing something?

BTW, I am using the demo/auth.py

**Comment by jmoldow** [comment]
`OAuth2` and many of its subclasses accept a `store_tokens` argument. See https://github.com/box/box-python-sdk/blob/master/boxsdk/auth/oauth2.py#L42  : 

```
        :param store_tokens:
            Optional callback for getting access to tokens for storing them.
        :type store_tokens:
            `callable`
```

You can pass in a callback which stores the refresh token into some sort of secure storage.

Then, when your app starts up, if there is a stored refresh token, it can pass it as the `refresh_token` argument to the constructor, and then immediately call `refresh()` instead of going through browser authentication.

**Comment by susamn** [comment]
Thanks a lot. It works

**Comment by WobbyChip** [comment]
so I have only one question how to import this in my project because I get an error -> NameError: name 'refresh' is not defined
