### ISSUE TITLE
write a script to send files to box application by automatic developer token generation

### ISSUE THREAD

**Issue by kira510** [box/box-python-sdk#205]
Requirement: I need a script that sends files to box.

So far, i managed to send the files to box by following https://docs.box.com/docs/getting-started-box-integration . I am using box-python-sdk to acheive this, but i have to use this developer token which is active only for 60 min for authenticaton. I have to generate a developer token everyday to run this script.

    oauth = OAuth2(
         client_id=CLIENT_ID,
         client_secret=CLIENT_SECRET,
         access_token=DEVELOPER_TOKEN,
         ) 
client = Client(oauth)

I cannot set the redirect URI as am not running an application on a server, am just running this script using "python box.py ". Is there a way to refresh the developer token in my script?

**Comment by Jeff-Meadows** [comment]
Please try the `DevelopmentClient` (mentioned here in the readme https://github.com/box/box-python-sdk#developer-token-client).

By default, it asks you for a developer token on standard input, and will ask you again on standard input whenever the token expires. Of course, you can modify the default behavior as well.

Hope that helps.

**Comment by kira510** [comment]
Hello @Jeff-Meadows 
Yes i have used this, but the requirement is that i have to run this script on a daily basis, entering the developer token manually is not an option for me. Can this actually be done a script?

Or should i develop an application whose URL should be configured as the redirect url on box side?

**Comment by skchronicles** [comment]
@Jeff-Meadows Is this an update to this? I am running into the same issue. I cannot continue entering a developer token from standard input.

**Comment by Jeff-Meadows** [comment]
Box supports different application auth types. The OAuth2 auth type isn't appropriate for a daily script, as you've noticed, because it expects user interaction. More appropriate would be JWT or Client Credentials auth, both of which are supported by the Python SDK now. 

Client credentials auth is covered here https://box.dev/guides/authentication/client-credentials/
And is implemented here: https://github.com/box/box-python-sdk/blob/main/boxsdk/auth/ccg_auth.py
