### ISSUE TITLE
Cannot upload file to folder other than root. 

### ISSUE THREAD

**Issue by nataliagalant** [box/box-python-sdk#341]
```
client.folder("0").upload("C:/Users/ngalant/Desktop/vid_play2.PNG", "vid_play2.PNG")
<Box File - 319716586629 (vid_play2.PNG)>
```
Throws no errors (although I am not an admin so I can't confirm the file is actually in the root directory). When I attempt to upload the same file into a folder shared with me: 
```
client.folder("63624631").upload("C:/Users/ngalant/Desktop/vid_play2.PNG", "vid_play2.PNG")

boxsdk.exception.BoxAPIException:
Message: Not Found
Status: 404
Code: not_found
Request id: 9a6w4fvebuldjsu
Headers: {'Date': 'Tue, 18 Sep 2018 19:58:49 GMT', 'Content-Type': 'application/json', 'Content-Length': '315', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, no-store', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Accept-Encoding', 'Age': '0'}
URL: https://upload.box.com/api/2.0/files/content
Method: POST
Context info: {'errors': [{'reason': 'invalid_parameter', 'name': 'parent', 'message': "Invalid value 'd_63624631'. 'parent' with value 'd_63624631' not found"}]}
```

Why the "d_" in front of the folder ID? Are there some permissions I haven't appropriately configured?

**Comment by carycheng** [comment]
Hey @nataliagalant, 

Thank you writing in - Wanted to grab a bit more context from you. 

1.) How are you generating your token and what scopes do you have enabled? (You can view this in your developer console)

2.) Do you have access to the folder you are uploading into? I would double check to make sure the user or token of the user you are making this upload call with are in fact invited onto the folder with the right permission level. 

Let us know, thanks!

**Comment by nataliagalant** [comment]
Thanks so much for the help!

1.) I am authenticating with JWT and I have the following scopes enables:
![image](https://user-images.githubusercontent.com/15127102/45714268-1d243700-bb5f-11e8-997e-13aff6e2cb12.png)


2.) I have access to the folder I am uploading to but I suppose the developer-token that gets generated would not. How do I go about setting up these permissions?

**Comment by carycheng** [comment]
Hey @nataliagalant, 

You have two options here:

1.) If you only intend on working in your own Box account we would recommend you use the ['as-user' header ](https://github.com/box/box-python-sdk/blob/1.5/README.rst#as-user) with a user that has been invited into that folder. 

2.) The second way would be to invite your service account(the token you are using with the developer account) into that specific folder. You can retrieve the service account email from the Content Manager tab in admin console by searching your app name.
<img width="1239" alt="screen shot 2018-09-18 at 1 33 31 pm" src="https://user-images.githubusercontent.com/6364733/45714861-af204580-bb47-11e8-897a-2dfb936d1f4f.png">

**Comment by nataliagalant** [comment]
@carycheng  I'm not sure I follow (I am not an enterprise admin but I can contact the admin when I have enough information). I thought the token gets generated upon authentication? Is there a permanent token associated with the app (client id?) that I can permission to the folder or would permissioning the "service account" allow app-access to that folder? 

My intention is to automate file uploads to box without any user intervention, which is why I chose JWT authentication. I am uploading to personal folder

**Comment by carycheng** [comment]
Hey @nataliagalant, 

It seems like the problem here is that your personal account has access to that folder but your application which uses a separate account (service account) does not have access. You can:

1.) Ask your admin to invite the service account into that specific folder you are attempting to upload into, that way you can use that token you are currently using to perform upload actions.

2.) If there is not a specific folder that already exists in which you are trying to upload into, you can use the service account to create a folder and then invite all necessary collaborators into that folder via service account token. You can then use the service account token to do your uploading.

3.) You can also have the service account as-user into a specific user on that folder you are attempting to upload to (The user will need sufficient permission levels). The as-user capability is where you allow the service account to make calls  as another user. You can read more about it [here](https://developer.box.com/reference#as-user-1). You can have the service account to impersonate your own account and invite itself.

```python
    service_user = client.user().get()
	your_user = client.user('YOUR_USER_ID')
    collab_folder = client.as_user(your_user).folder(folder_id='SOME_FOLDER_ID').get()
	collaboration = collab_folder.add_collaborator(service_user, CollaborationRole.EDITOR)
```

Let us know if this works or if you run into any other issues, thanks!
