### ISSUE TITLE
User list in 2.0 is not backward compatible

### ISSUE THREAD

**Issue by volker-fr** [box/box-python-sdk#364]
I use the bellow code. It gets all the users from the app and selects one to use. In 1.5.5 it was a correct list and works fine.

```
    ....
    box_auth = boxsdk.JWTAuth(....)
    client_box_app = boxsdk.Client(box_auth)
    ....
    app_users = client_box_app.users()
    if len(app_users) > 1:
        logging.warning("More as one app user found. Using only the first user: %s" % len(app_users))
        app_user = app_users[0]
    elif len(app_users) == 1:
        app_user = app_users[0]
    else:
        # We need to create a user now
        app_user = client_box_app.create_user(box_app_user_name)
```

Since the recent 2.0 changes the same code results in an error:

```
Traceback (most recent call last):
  File "/tools/box-downloader.py", line 182, in <module>
    client_app_user = get_client_box_app_user(config, client_app)
  File "/tools/box-downloader.py", line 84, in get_client_box_app_user
    if len(app_users) > 1:
TypeError: object of type 'LimitOffsetBasedObjectCollection' has no len()
```

The (temporary) workaround is obviously to hardcode the box-sdk version in `requirements.txt`
```
boxsdk[jwt]<2.0
```

**Comment by mattwiller** [comment]
@volker-fr That's correct — as noted in the [changelog](https://github.com/box/box-python-sdk/blob/master/HISTORY.rst), we've standardized all methods that return collections to return an iterable `BoxObjectCollection` instead of loading all objects into memory at once.  You can always get the full `list` by doing something like this:

```python
app_users = [user for user in client_box_app.users()]
```  

In general, there are a number of breaking changes in v2.0.0; you may need to make some changes to your application in order to upgrade.

**Comment by jmoldow** [comment]
Hi @volker-fr , we made an intentional breaking change in the 2.0 release in order to improve our paging interface across the entire SDK, and hopefully make it much easier to correctly page through a collection.

See our `HISTORY` file:
> The following methods now return iterators over the entire collection of returned objects, rather than a single page:
>
>    client.users()
>    client.groups()
>    client.search().query()
>    folder.get_items()
> [....]
> Added BoxObjectCollection and subclasses LimitOffsetBasedObjectCollection and MarkerBasedObjectCollection to more easily manage paging of objects from an endpoint. These classes manage the logic of constructing requests to an endpoint and storing the results, then provide __next__ to easily iterate over the results.

The new paging interface can be found here: https://github.com/box/box-python-sdk/blob/master/boxsdk/pagination/box_object_collection.py

Since the new object is an iterable, one quick way to fix the problem would be to do `app_users = list(client_box_app.users())`. In your case, since you only expect 1 user, that should be safe to do. In general, that wouldn't be safe, because that would block until all pages could be fetched from the API.

Another way to restructure your code would be with something like this:

```python
    app_users_iterator = client_box_app.users()
    app_user = next(app_users_iterator, None)
    if app_user is None:
        # We need to create a user now
        app_user = client_box_app.create_user(box_app_user_name)
    if next(app_users_iterator, None) is not None:
        logging.warning("More as one app user found. Using only the first user")
```

**Comment by volker-fr** [comment]
Thanks. I just started to look in the code and noticed that the return type was changed from a list of the User class to the `MarkerBasedObjectCollection` class.

It's actually my own fault to not look into the HISTORY file first.

I appreciate the quick responses. Learned my lesson.
