### ISSUE TITLE
Importing boxsdk cause TypeError

### ISSUE THREAD

**Issue by mitsuo0114** [box/box-python-sdk#400]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When I try to use boxsdk, the error occurred when I just run "import boxsdk"

### Versions Used
boxsdk==2.1.0
Python 3.6.2 

### Steps to Reproduce
Execute python, and just use "import boxsdk"

### Error Message, Including Traceback
```
C:\Python36-32\python.exe
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import boxsdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-32\lib\site-packages\boxsdk\__init__.py", line 5, in <module>
    from .auth import JWTAuth, OAuth2
  File "C:\Python36-32\lib\site-packages\boxsdk\auth\__init__.py", line 5, in <module>
    from .cooperatively_managed_oauth2 import CooperativelyManagedOAuth2
  File "C:\Python36-32\lib\site-packages\boxsdk\auth\cooperatively_managed_oauth2.py", line 4, in <module>
    from .oauth2 import OAuth2
  File "C:\Python36-32\lib\site-packages\boxsdk\auth\oauth2.py", line 18, in <module>
    from ..exception import BoxOAuthException, BoxAPIException
  File "C:\Python36-32\lib\site-packages\boxsdk\exception.py", line 95, in <module>
    class BoxOAuthException(BoxException):
  File "C:\Python36-32\lib\site-packages\boxsdk\exception.py", line 128, in BoxOAuthException
    network_response = attr.ib(default=None, repr=False, type=NetworkResponse)
TypeError: attr() got an unexpected keyword argument 'type'

```
[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by mitsuo0114** [comment]
Hi, community
I have met above error. please help me and let me know if I should try to change something or post more info.
Thanks in advance

**Comment by carycheng** [comment]
Hello @mitsuo0114, 

Thank you for writing in! We looked into it and we believe that this issue you are having is due to a dependency oversight on our part. Apologies! It seems that we are requiring the `attrs` library as having the minimum version of 16.0.0. However, in reality we need 17.3.0. This is because we need one of the attributes, specifically `type` that was newly introduced in the latter release. In the immediate future we can take these steps.

1. To get unblocked immediately please update your attrs lib to minimum 17.3.0. (I believe the newest is 18.2.0).

2. We have a pr out now with the update that we can push out with our next release that should resolve you issue at #401 

Thank you! And we apologize for any inconvenience this may have caused.

**Comment by mitsuo0114** [comment]
@carycheng Thank you! Understood, I will append attr dependency by myself.
I'm looking for next release :)

Can I close this issue? or will you?

Thanks and Regards,

**Comment by carycheng** [comment]
Thank you for writing in @mitsuo0114! Let us know if you have any other issues
