### ISSUE TITLE
Search does not use limit

### ISSUE THREAD

**Issue by masics** [box/box-python-sdk#437]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When I use limit=1 to the search query it still generates a lot results.
### Versions Used
Box Python SDK: 2.5.0
Python: 3.7.3

### Steps to Reproduce
    search_results = client.search().query(
        "'" + name + "'",
        limit=1,
        offset=0,
        ancestor_folders=[client.folder(folder_id='XXXXXXXXX')],
        result_type='folder',
        content_types='n'
    )
    collectionSize = 0;
    for item in search_results:
        collectionSize += 1
        item_with_name = item.get(fields=['name', 'path_collection'])
    print(collectionSize)

### Error Message, Including Traceback
I can get thousands of results in collection.

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@masics Please see https://github.com/box/box-python-sdk/issues/366 — the `limit` parameter refers to the limit of search results fetched per API call, not the total number of results that will be produced by the iterator.  If you only want the first item out of the iterator, you can just call `search_results.next()` to get it.

**Comment by masics** [comment]
I see. How I search exact name within hierarchy? Like "All
Files/folder1/folder2"?

**Comment by mattwiller** [comment]
@masics Unfortunately, there is not an exact way to perform that sort of search.  It looks like you're already trying to use quotes to get an exact search for the name of the item you're looking for, but I think you'll need to use double quotes instead of single quotes for that.  You should be able to get the most precise search results and then iterate through the results to find the exact folder you're looking for like this:
```python
search_results = client.search().query(
    '"' + name + '"',
    ancestor_folders=[client.folder(folder_id='XXXXXXXXX')],
    result_type='folder',
    content_types='name',
    fields=['name', 'path_collection']
)
for item in search_results:
    path = '/'.join([folder.name for folder in item.path_collection])
    if path == 'All Files/folder1/folder2':
        # `item` is the one you're looking for!
```

**Comment by masics** [comment]
I tried all kinds of quotes. If name is a single letter, the result will
include all files with that letter in the name. In my case it is thousands
of files and it takes minutes and sometimes 10s of minutes.

**Comment by mattwiller** [comment]
@masics Ah, if your folder name is a single letter then that does seem like it may be [expected behavior](https://community.box.com/t5/Managing-Files-and-Folders/Search-for-Files-Folders-and-Content/ta-p/19269#searchtips).  You should be able to speed up your code overall by using `fields` on the search query itself rather than making a separate call to get each item (see my sample code above), but otherwise this isn't an SDK issue but a limitation of the API.
