### ISSUE TITLE
SSL Verification Issue

### ISSUE THREAD

**Issue by sdeshpande** [box/box-python-sdk#438]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
SSLCertVerificationError While connecting using OAuth2 
Our company does SSL Decryption on all workstations in our office. While connecting to BOX SDK I am getting following error. 
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.box.com', port=443): Max retries exceeded with url: /2.0/users/me (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))) 
 Is it possible to add something similar to "SSLVerify = False" while authenticating ? 

### Versions Used
Box Python SDK: 2.5.0 
Python: 3.7.3 

### Error Message, Including Traceback
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.box.com', port=443): Max retries exceeded with url: /2.0/users/me (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@sdeshpande The approach we would recommend here is to get the certificate that's being injected by whatever is doing the SSL decryption and set the `REQUESTS_CA_BUNDLE` environment variable to the path to that certificate (or a directory of CA certificates) when running your program.  If you really want to disable all SSL validation, which we __do not recommend__ because it is insecure, you can set the `PYTHONHTTPSVERIFY` environment variable to `0`.

**Comment by sdeshpande** [comment]
Thank you. This is very helpful.
