### ISSUE TITLE
Instead of bottle.py, can I use djagno for OAuth2

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#442]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Versions Used
Box Python SDK: 
Python: 

### Error Message, Including Traceback

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by c-rei** [comment]
I'v known that the bottle was used to OAuth2 authentication, but I wand to use Django for our product, can I get some sample code for Django instead bottle.

Description of the Issue
Versions Used
Box Python SDK:  2.5.0
Python: 3.6.8
Django: 2.2.1

**Comment by mattwiller** [comment]
@c-rei Yes, you can certainly use Django instead of Bottle for the web server component of OAuth2.  Unfortunately, we don't have any sample code for Django, but the Bottle sample code shows how to set up a web server to listen for the auth code from the Box API, and exchange the auth code for a token pair — that part is the same no matter which web server library you use.
