### ISSUE TITLE
boxsdk.object' has no attribute 'collaboration_whitelist_entry'

### ISSUE THREAD

**Issue by mukesh884** [box/box-python-sdk#489]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am getting below error while trying to execute my script after convering .py to exe.

Python file works perfect after converting to exe using pyinstaller  it shows below error.

Traceback (most recent call last):
  File "IFL-Box-Upload.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\sesa564604\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\boxsdk\__init__.py", line 8, in <module>
AttributeError: module 'boxsdk.object' has no attribute 'collaboration'
[21112] Failed to execute
 

### Versions Used
Box Python SDK: 2.7.1
Python:  3.8.1

**Comment by msilano** [comment]
Hi @mukesh884.

I've hit this issue before as well.  You have to explicitly import those specific objects so that pyinstaller (or cx_freeze) can properly pick up the references.

You can do that by including the following lines:

# We need explicit imports for these objects so that cx_freeze
# and pyinstaller will pick up all of the needed files in the package.
import boxsdk.object.comment
import boxsdk.object.collection
import boxsdk.object.collaboration
import boxsdk.object.collaboration_whitelist_entry
import boxsdk.object.collaboration_whitelist_exempt_target
import boxsdk.object.device_pinner
import boxsdk.object.enterprise
import boxsdk.object.events
import boxsdk.object.event
import boxsdk.object.file
import boxsdk.object.file_version
import boxsdk.object.file_version_retention
import boxsdk.object.folder
import boxsdk.object.group
import boxsdk.object.group_membership
import boxsdk.object.legal_hold
import boxsdk.object.legal_hold_policy
import boxsdk.object.legal_hold_policy_assignment
import boxsdk.object.metadata
import boxsdk.object.metadata_cascade_policy
import boxsdk.object.metadata_template
import boxsdk.object.recent_item
import boxsdk.object.retention_policy
import boxsdk.object.retention_policy_assignment
import boxsdk.object.search
import boxsdk.object.storage_policy
import boxsdk.object.storage_policy_assignment
import boxsdk.object.task
import boxsdk.object.task_assignment
import boxsdk.object.terms_of_service
import boxsdk.object.terms_of_service_user_status
import boxsdk.object.user
import boxsdk.object.upload_session
import boxsdk.object.watermark
import boxsdk.object.web_link
import boxsdk.object.webhook

Good luck!

**Comment by mukesh884** [comment]
@msilano 
It Worked thanks a lot....
