### ISSUE TITLE
Using JWT

### ISSUE THREAD

**Issue by masics** [box/box-python-sdk#511]
I have a config.json downloaded from the development console. When I create a client with this file everything is working just fine.
But after some time the api calls are being rejected because of the token. Why this is happening? How I can make it working constantly without reloading the application?

**Comment by sujaygarlanka** [comment]
If you use the config.json and follow the steps [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#server-auth-with-jwt), this should not happen. Are the error codes returned 401?

**Comment by masics** [comment]
I get: 404 with following message:
"OPTIONS https://api.box.com/2.0/files/content" 404 320
{'Date': 'Thu, 21 May 2020 03:44:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000
', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'BOX-REQUEST-ID': 'REDACTED', 'X-Powered-By': 'PHP/7.3.15'}
{'code': '---ound',
 'context_info': {'errors': [{'message': "Invalid value 'd_111111111111'. "
                                         "'item' with value 'd_111111111111' "
                                         'not found',
                              'name': 'item',
                              'reason': 'invalid_parameter'}]},
 'help_url': 'http://developers.box.com/docs/#errors',
 'message': 'Not Found',
 'request_id': 'REDACTED',
 'status': 404,
 'type': 'error'}

(item value was changed to keep privacy)

When I change authentication to OAuth2 everything is working fine (no other changes).

**Comment by sujaygarlanka** [comment]
@masics It seems that you are making a bad request. The item ID you are sending is incorrect. Maybe your JWT code makes a call that sends the wrong item ID that your OAuth code does not have.

**Comment by masics** [comment]
The only difference is the authentication mode. The rest of the logic knows
nothing about it.

**Comment by sujaygarlanka** [comment]
@masics Is this still an issue?

**Comment by masics** [comment]
Yes. I can't use it.

**Comment by sujaygarlanka** [comment]
@masics I think your issue is that your app is accessing the Service account and you are logging into a Box User account. More information about this can be found [here](https://developer.box.com/guides/authentication/jwt/). I would log into your dev console, click on your app, and click on General. I have attached a screen shot to the page you will arrive at below. Find the user ID (the one covered by the red box), and use that to create a client as shown [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#as-user). Once that is done, you will have a client that will access the user account you log into rather than the service account. This should fix your issue. Feel free to re-open this if this does not solve your issue.
<img width="1435" alt="Screen Shot 2020-06-29 at 12 45 34 PM" src="https://user-images.githubusercontent.com/21188938/86040441-0d16d800-ba12-11ea-9aa5-ad052414cdf7.png">
