### ISSUE TITLE
'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by samkuehn** [box/box-python-sdk#521]
### Description of the Issue
Passing an integer to an item raises `'int' object has no attribute 'isdigit'`.  This bug was introduced in 2.9.0 and is related to this line: https://github.com/box/box-python-sdk/blob/17096848c03877c584eac0f94d9e3a0fe2f464a7/boxsdk/object/item.py#L762

The `validate_item_id(item_id)` method is expecting a string and calling isdigit on it.  I think we should be able to pass in an integer, as we have been able to in the past.

Perhaps we could add this to `validate_item_id(item_id)`?
```
if isinstance(item_id, int):
    return
```

### Steps to Reproduce
Client().folder(123).get()

### Expected Behavior
Should be able to get an item by integer

### Versions Used
Python SDK: 2.9.0
Python:  3.7.7

**Comment by PJSimon** [comment]
Hi @ReporterGitHubUserName,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by abloomston** [comment]
+1 to this issue, I'm seeing this as well. Looking forward to a status update @PJSimon 🙏

**Comment by holtat** [comment]
I ran into this issue and it seems you need to change your id from an int to a string (e.g. `Client().folder('123').get()`)

Hope this helps

**Comment by sujaygarlanka** [comment]
@abloomston @holtat @samkuehn Issue has been fixed and merged by #530. Will do a release sometime soon.

**Comment by Jeff-Meadows** [comment]
Just my two cents, but the Box API documents these IDs as strings, not ints. Therefore, the API reserves the right to use strings that aren't compatible with integers.

The bug here is the client-side ID "validation" that imposes the restriction on IDs that they must by numeric.

I think the SDK should do 1 of 2 things:

1. Disallow passing an int as an ID
2. Allow it and just convert it to string.

I think the SDK is doing the wrong thing by insisting that clients pass numeric strings to an API documented as accepting strings.

**Comment by danlamanna** [comment]
@sujaygarlanka Any update on when a release will be cut?
