### ISSUE TITLE
File.move() command should give id of conflicting File in BoxApiException

### ISSUE THREAD

**Issue by saaqibz** [box/box-python-sdk#58]
If I do myFile.move(myFolder) where my file is a box file object and folder is a box folder object with a file in it that's the same name as myFile, the I get a BoxApiException with a status of 409 conflict.

It would be nice if the exception in it's context_info included the ID of the conflicting file.

This is the behavior that I get when I try to make a new file in a folder that has an existing file with the same name. the exception object would have the id of the conflicting file. It would be more consistent and cost me less search calls if move did the same thing.

**Comment by jmoldow** [comment]
The ``context_info`` object comes directly from the API response. If it doesn't include the ID of the conflicting file, that is because the API isn't providing it.

I can pass this request along to the API team, and see if they can start doing this.

Without API support for this, the SDK would need to do the same search call that you are currently doing, which wouldn't make sense to add to the library.

**Comment by saaqibz** [comment]
If you could pass that along that would be great. I wasn't sure where to post it. Thanks!

**Comment by jmoldow** [comment]
No problem. I just got in contact with our API team and asked if they can implement this.
