### ISSUE TITLE
Unable to Generate AUTH_CODE

### ISSUE THREAD

**Issue by dglindner2** [box/box-python-sdk#606]
Hey Box Team,

I'm trying to follow the steps in the readme file for OAUTH2 verification. After entering my **auth_url** into the browser, I am redirected to a screen that asks me if I want to grant access to Box. When I grant access to box, I expect to get redirected to another URL that has my auth_code in it as described below

**_If you navigate the user to the auth_url, the user will eventually get redirected to http://YOUR_REDIRECT_URL?code=YOUR_AUTH_CODE. After getting the code, you will be able to use the code to exchange for an access token and refresh token._**

However, I just get redirected to https://app.box.com/folder/0 every time. Could someone let me know what I need to do differently in order to access my auth_code?

Thanks,

George

**Comment by mwwoda** [comment]
Hi @dglindner2 

AuthCode should be present in the URL after redirect when you grant access to box. Did you set up the OAuth redirect url in developer console for your app? Is this the same as the one you use when calling `oauth.get_authorization_url('http://YOUR_REDIRECT_URL')`?

Thanks,
@mwwoda

**Comment by mwwoda** [comment]
The **OAuth 2.0 Redirect URI** in the first screenshot is actually the URL you will be redirected to after granting Box permissions. That's why you are redirected to https://app.box.com/folder/0. If you want to be redirected to your website you should change it to e.g. https://mywebsite.com then your code should also look like this 
`redirect_uri = https://mywebsite.com`
`auth_url, csrf_token = sdk_getauthorization_url(redirect_uri)`
Then when you access the auth_url and grant the permission you will be redirected to https://mywebsite.com?code=auth_code that will contain auth_code at the end of the url. You can use this code to get access token and refresh token.
Hope that helps!

**Comment by mwwoda** [comment]
I presume that the problem was resolved. If you continue to have issues, feel free to re-open this issue.
