### ISSUE TITLE
Can't get any external user

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#632]
I can't get any information about external users with below code,

users = client.users(user_type='external')

It just return the empty.

### Versions Used
Python SDK:  2.12.1
Python:  3.8.10

Thanks any help.

**Comment by arjankowski** [comment]
Hi @c-rei,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@arjankowski

**Comment by arjankowski** [comment]
Hi @c-rei ,

The documentation of this endpoint [https://developer.box.com/reference/get-users/](https://developer.box.com/reference/get-users/) says, that 
if `user_type=external`, then you also need to pass `filter_term`.

```
external returns all external users for whom the login matches the filter_term exactly.
```

What is more, in `filter_term` [here](https://developer.box.com/reference/get-users/#param-filter_term) is written:

```
For externally managed users, the search term needs to completely match the in order to find the user, and it will only return one user at a time.
```

For externally managed users, the search term needs to completely match the in order to find the user, and it will only return one user at a time.
