### ISSUE TITLE
Error authenticating to Box

### ISSUE THREAD

**Issue by fcarias38** [box/box-python-sdk#670]
After reviewing your suggested resolution we concluded that it does not apply to our current issue because we aren't changing networks or using VPN on these machines. In fact, our computers are working most of the time and sporadically get this error. Can you please provide an alternative solution?

**Comment by mgrytsai** [comment]
Hi @fcarias38,

I am not sure about which issue you refer to and I couldn't find it. Could you please describe or  link the issue you are facing?

Thanks in advance!

**Comment by fcarias38** [comment]
It is actually under my company information Vulcan Materials. Do I need create a GitHub account under my work email ?

Sent from my iPhone

On Jan 31, 2022, at 3:33 PM, Mike Grytsai ***@***.***> wrote:

﻿

Hi @fcarias38<https://github.com/fcarias38>,

I am not sure about which issue you refer to and I couldn't find it. Could you please describe or link the issue you are facing?

Thanks in advance!

**Comment by mgrytsai** [comment]
No need to create a github account with your company email address. But it would help if you can link or briefly describe the issue you are facing. As I am not sure where you posted the problem description.

**Comment by fcarias38** [comment]
We are occasionally getting the following error from our python script that uploads data from our point of sale sites to Box:
​Error authenticating to Box: HTTPSConnectionPool(host='api.box.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EC31E254E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Stopping and starting our script does not seem to help. Usually within a day or two, the problem goes away until the next occurance.

**Comment by arjankowski** [comment]
Hi @fcarias38, we will try to help you with this issue, but first we have some questions that will help us find a solution?

**1)**
When did this error start appearing? Was it due to some update of our SDK or software on your side?

**2)**
It's hard to say what's wrong now, because the error comes from trying to connect through an external library and not directly from our code . Therefore, I would like you to run this CURL command as soon as the described error occurs due to the execution of your script:

```
curl -i -X GET "https://api.box.com/2.0/users/me" -H "Authorization: Bearer <! Insert Token Here!>
```

Please let us know the result and then we will continue to investigate this issue.
