### ISSUE TITLE
events 

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#74]
the events module tells me that a tag was created but it does not show the contents of the tag i am trying to move files based on a approved or rejected tag and the tag does not show up if the users tags using the gui 

```python
def event_python():
    Ev=client.events().get_events(limit=1000,stream_position='now')
    nxt_stream_pos=Ev['next_stream_position']
    print (nxt_stream_pos)
    event_list=client.events().get_events(limit=1000,stream_position=nxt_stream_pos)
    jsone= (event_list['entries'])
    dicts={}
    for k in jsone[0]: 
        if k == None :
            exit
        dicts[k]=[d[k]for d in jsone]
    et=dicts['event_type']
    item_type=dicts['source']
    return et,jsone,nxt_stream_pos
```

thank you

**Comment by jmoldow** [comment]
Hi @danyal123 ,

Our events methods always return the full set of information that is available in the Box API's event stream. See https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#L47 and https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#L74. If you aren't seeing the information that you're looking for, then the Box API event stream is not providing it.

If this is in fact the case, then in order to get the tags applied to a file, you'll need to do something like:

```python
folder_id = ...  # from the event
tags = client.folder(folder_id).get(fields=['tags']).tags
```

**Comment by danyal123** [comment]
is the method you recommended applicable to files or is limited to just folders

**Comment by jmoldow** [comment]
The event should tell you the id and type of the item. I'm not familiar with tag creation events in particular, but I'd expect the JSON to contain something like this: ``{..., 'id': '1234', 'type': 'file', ...}`` or ``{..., 'id': '5678', 'type': 'folder', ...}``. Then in the case of the file, you can do ``tags = client.file(file_id).get(fields=['tags']).tags``.

Or you can do both of them, with something like

```python
item_id = ... # from the event
item_type = ... # 'file' or 'folder', from the event
item = getattr(client, item_type)(item_id).get(fields=['tags'])  # An instance of Item. Will actually be either an instance of Folder or File.
tags = item.tags
```

**Comment by danyal123** [comment]
thank you
