### ISSUE TITLE
ConnectionResetError(10054) when I get some information about the contents.

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#757]
I want to get some information of my contents, so I do tow steps like below.

1 step:
I got a contents list, and output them to csv file with item name, id, and type.
I used "items = folder.get_items()", and with recursion route, I can got 40,000 items.

2 step:
I want to get the collaborations and  shared links using "item.get_collaborations()" and "item.shared_link" through my csv file that got on step one.
 
After about 2 hours, I got the error like that "'Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)". So I can't complete my process. 

I want to known what's wrong with my process. How can I avoid this error.

### Versions Used
Python SDK: 3.2.0
Python: 3.8.8
and my csv file.
![csv](https://user-images.githubusercontent.com/26074496/183563237-44f3ff3e-7787-47b5-a0a2-c5c0c71ef308.png)

**Comment by c-rei** [comment]
Hi sir
This problem occurs after 2 hours and sometimes, even immediately after execution.
My code samples like this,
![err1](https://user-images.githubusercontent.com/26074496/183782137-d3fcf68b-0e14-409e-8425-5c2325ad8c2f.png)
![err2](https://user-images.githubusercontent.com/26074496/183782144-3059c0b0-ceac-4302-98f5-753acedd148a.png)
![err2](https://user-images.githubusercontent.com/26074496/183782146-226bddfc-179c-4a17-8b98-bb8cb8fb9614.png)
![err1](https://user-images.githubusercontent.com/26074496/183782147-59793dfa-0582-4a48-94e3-2dc6c4bf628e.png)

**Comment by c-rei** [comment]
And I have  another problem, it occurs after long run with same code.

('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

**Comment by mwwoda** [comment]
So looking at the errros you are getting, the fact that the problem is non-deterministic and after talking with other team members I think that it is most likely a client or server problem. I don't see much impact the sdk can have. There are a few steps you can take to try to solve your issue:
1. Troubleshoot the network connection further. You may get some of these errors because, for example, you lost your connection while executing code. Make also sure that your e.g. firewall is not blocking any outgoing/outgoing requests.  Make sure that your environment is not causing these issues.
2. If increasing the number of retry attempts doesn't help, you can try wrapping api calls in a try/except clause. In the except block, you can try to establish a new connection to the box api. This could help if there is some problem with existing connection.
3. If you are still encountering the problem and you think it's server-side problem, I would advise you to contact our backend team. You can create a ticket at https://support.box.com/hc/en-us/requests/new so that they can investigate it further.

**Comment by c-rei** [comment]
Thanks your advise. But I'm not sure your "wrapping api calls" means. To try wrapping api calls in a try/except clause, I want to do like a sample below?
num = 0
while True:
    try:
        a_folder = client.folder(folder_id="123456789").get()
        break
    except requests.RequestException:
        if num < 5:
            num += 1
            continue
        else:
            raise
    except Exception:
        raise
