### ISSUE TITLE
I can't get ITEM_PREVIEW and ITEM_DOWNLOAD event without owner role

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#795]
I use the event api learning the usage doc, like below.
stream_position = 0
events = client.events().get_events(stream_position=stream_position)
stream_position = events['next_stream_position']
for event in events['entries']:
    print(f'Got {event.event_type} event that occurred at {event.created_at}')

If I have  owner role, I can get ITEM_UPLOAD, ITEM_PREVIEW , ITEM_DOWNLOAD and other event type.
But if I have co-owner or editor role as a collaborator, I can't get ITEM_PREVIEW and ITEM_DOWNLOAD events created by other user. Even this situation I also can get ITEW_UPLOAD events and other event type.

So I want to known what's wrong with my usage, I just want to get ITEM_PREVIEW and ITEM_DOWNLOAD events created by other user with in the situation that I don't have owner role, just as a collaborator with co-owner or editor role.

Thanks any help.

### Versions Used
Python SDK: 3.5.0
Python: 3.8.10

**Comment by mwwoda** [comment]
I'm not sure about this particular use case, but it may be due to different roles as owner and co-owner/editor are still different roles - see https://support.box.com/hc/en-us/articles/360044196413-Understanding-Collaborator-Permission-Levels, so they may have different event feed. You can also try to see if you get different results when using EnterpriseEvents.

I would advise you to consider posting this question on our forums https://support.box.com/hc/en-us/community/topics as it looks more API related than SDK related.

**Comment by c-rei** [comment]
Thanks your response, I will try EnterpriseEvents and let you known the results.
