### ISSUE TITLE
Not able to Lock files

### ISSUE THREAD

**Issue by Sevillesilveira** [box/box-python-sdk#858]
The code is as below:
lock = client.folder(folder_id='233490176640').create_lock()
print(f'Created a lock with ID {lock.folder.id}')

The output:
![image](https://github.com/box/box-python-sdk/assets/121432447/b2c7d351-afb2-4b58-b421-8a6f7383271a)

But I am still able to move the files in this particular folder and even delete it. 
Kindly let me know how to resolve this issue.

**Comment by Sevillesilveira** [comment]
Thank you @congminh1254
I was able to lock the folders later on but the files in these folders can still be moved. 
Is there a way to prevent the files in the locked folders from being edited or moved to a different location.

**Comment by congminh1254** [comment]
Hi @Sevillesilveira 
Sorry for the confusion, but the folder locked is not affecting for the file inside folder. If you want to lock files, unfortunately it's not able to do it in single request. 
By using this `client.file(file_id).update_info` method, you can create lock for single file with an expiring time. This prevents the item from being moved, renamed, or otherwise changed by anyone other than the user who created the lock.
Best,
Minh

**Comment by Sevillesilveira** [comment]
Hi @congminh1254 
Could you provide me with the code to prevent files from being moved. I am unable to get the file information in JSON format in VS Code and I don't know how each parameter is named for the files. 
![image](https://github.com/box/box-python-sdk/assets/121432447/551e4aa8-ca2c-4b17-af11-a8510ae6b599)
The above image is the output I get after for the file information which is only the name and id of the file.
