### ISSUE TITLE
Prevent files from moving

### ISSUE THREAD

**Issue by Sevillesilveira** [box/box-python-sdk#859]
I am able to lock files using python-sdk code but the files after getting locked can still be moved from one folder to another. Is there any loc to prevent this from happening.

**Comment by congminh1254** [comment]
Hi @Sevillesilveira 

From the document: `This prevents the item from being moved, renamed, or otherwise changed by anyone other than the user who created the lock.`

So I think the lock is used for preventing other users do any changes for a shared folder, but as an owner of the lock, you can still make the changes. I think there is nothing you can do to prevent the owner of the file do changes on the file.

Best,
Minh

**Comment by congminh1254** [comment]
Hi @Sevillesilveira 

I have just confirmed with the team and they provided this (Understanding Collaborator Permission Levels
)[https://support.box.com/hc/en-us/articles/360044196413-Understanding-Collaborator-Permission-Levels].

So the lock prevents the item from being moved, renamed, or otherwise changed, until someone have the permission remove the lock.

**Comment by Sevillesilveira** [comment]
Hi @congminh1254 

Thank you for the support.
