### ISSUE TITLE
document conda-forge install option

### ISSUE THREAD

**Issue by akrherz** [box/box-python-sdk#862]
I've gotten `boxsdk` added to conda-forge as [conda-forge/boxsdk-feedstock](https://github.com/conda-forge/boxsdk-feedstock).  Perhaps this install option could be documented here?

> conda install -c conda-forge boxsdk

Please let me know if anybody here would like to be added as a maintainer to that feedstock.  I am happy to keep it going regardless :)

**Comment by mgrytsai** [comment]
Hi @akrherz ,

Thank you for making a new distribution option. Unfortunately, we can't include your source, since we don't control it and can't guarantee the source for our customers.

For your information, we also have a new version of python SDK which will replace the current one. You can take a look at it here [https://github.com/box/box-python-sdk-gen](https://github.com/box/box-python-sdk-gen) and, perhaps, you might want to consider using the new SDK as well.

**Comment by akrherz** [comment]
Thanks @mgrytsai for the response.  Some followups.

1. I've created a [box-sdk-gen-feedstock](https://github.com/conda-forge/box-sdk-gen-feedstock) now.  So `box-sdk-gen` can now be installed via `conda-forge`.
2. Anybody with a github account can sign up to help maintain the feedstock, so you folks could still have 'control' over this build.  I understand resources are thin, etc.  I'm happy to maintain both repos going forward.
3. From my perspective, `conda-forge` is a very significant player in the python packaging landscape.  On windows for example, it is a much better experience and more likely to work than `pypi`...

I totally understand what you are saying, so no worries.  Thanks!

**Comment by mgrytsai** [comment]
Thank you! Good to know it for the future.

**Comment by RoyiAvital** [comment]
Great to see the package in `conda-forge`. Indeed for Windows this is a better path than `pip`.
