### ISSUE TITLE
box to s3

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#93]

**Comment by danyal123** [comment]
I have a question is there a way to possibly move files from box to amazon s3 without having to go through the intermediate step of downloading the file to local machine,

**Comment by jmoldow** [comment]
The boxsdk does not support this, because the Box API does not support this. You must always initiate a download in order to direct your content somewhere, whether it be your computer, or S3, etc.

If you want to avoid creating a temp file on your hard drive and the file is small enough, you can use ``File.download_to()`` to direct the bytes to an in-memory data structure (such as ``io.BytesIO``), and then perform the upload from there. You can also use ``File.content()`` to get the ``bytes`` directly. But both of these methods will stream the full file contents into memory before you can re-upload them.

Another option for download is to do the following:

```python
from contextlib import contextmanager, closing
my_file = client.file(box_id)

@contextmanager
def content_chunks(file):
    url = file.get_url('content')
    with closing(file._session.get(url, expect_json_response=False, stream=True)) as box_response:
        yield box_response.network_response.response_as_stream.stream(decode_content=True)

# Usage example 1
with content_chunks(my_file) as chunks:
    for chunk in chunks:
        # Handle chunk

# Usage example 2
with content_chunks(my_file) as chunks:
    # Handle chunks
```

This will only download one chunk at a time, and will not download all the contents into memory. But then you'll need to figure out a way to do an upload with one chunk at a time. We use ``requests_toolbelt.multipart.encoder.MultipartEncoder`` to stream files from disk without loading the contents into memory; however, I don't know if this works with generators. You might be able to create a subclass of ``io.IOBase`` that wraps the generator and exposes the stream API, which can then be passed to ``MultipartEncoder``. Or there might be a library somewhere on PyPI that already does this. Or there might be an alternative to ``requests`` / ``requests_toolbelt`` that allows you to do stream uploading of a file based on a generator.
